### ISSUE TITLE
Quest TTS stop working (gives no sound but no error screen either)

### ISSUE THREAD

**Issue by RinaGordi** [z0fa/WoWQuestTTS#3]
Hi! As mentioned above, Quest TTS worked fine, but today it stopped working (It doesn't give any sound). Strange thing, but there is no error screen either.  

QuestTTS-1.17
Windows 10 19044
WoW 10.0.2.46658

Here is the list of what I've already tried:
1. Disable all addons
2. Turn QTTS off and on again
3. Delete cash
4. Turn computer off and on again
5. Delete addon, enter and exit game, reinstal addon and enter game again (+4th and 3rd points).
6. Instal older version (+5th, 4th and 3rd points)

**Comment by RinaGordi** [comment]
Forgot to mention that I also tried to use console command "/qtts play" and "/qtts stop" (but still no luck)

**Comment by z0fa** [comment]
Are you still having the issue with the latest varsion?

**Comment by RinaGordi** [comment]
The problem hasn't gone away. But, I found a way around it. 
If a glitch occurs and the voiceover stops working, I have to restart the game and minimise the window until the character is afk. It works in versions 16, 17 and 18. 
In the eighteenth version, the console command and book voicing stop working.

**Comment by z0fa** [comment]
Okay there was a bug with the book voicing, it is should be fixed in 1.19. For the other problem it could be something related to the game itself and not to the addon... When the issue happens again can you try the command /tts and check if you can hear somenthig? This is a native WoW command to enable/disable the tts of the chat, if this is broken too then there is somenthing wrong with the game and there isn't much I can do...

**Comment by RinaGordi** [comment]
Okay, I tried... and it really is a problem with game😅

Thanks a lot for your help!🥰

**Comment by z0fa** [comment]
Ahah okay, it's a very strange problem btw 🤔
You can try to send bug a report on the blizzard forums or within the game and maybe they can provide you a fix
